language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rodobkn/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rodobkn/docker-react npm run test